apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-app
  namespace: mern-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-app
  template:
    metadata:
      labels:
        app: mern-app
    spec:
      containers:
        - name: mern-app
          image: abdulmoiz2640/mern-app:latest
          ports:
            - containerPort: 5001
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
