apiVersion: v1
kind: Service
metadata:
  name: mern-app-service
  namespace: mern-namespace
spec:
  type: NodePort
  selector:
    app: mern-app
  ports:
    - port: 80
      targetPort: 5001
      nodePort: 30007
